version: '3'

services:
    miaoma-docs-postgresql:
        image: postgres:16-alpine
        container_name: miaoma-docs-postgresql
        ports:
            - '5433:5432'
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_DB=postgres
            - POSTGRES_PASSWORD=xiaoer
            - TZ=Asia/Shanghai
        volumes:
            - ./postgresql_data:/var/lib/postgresql/data

networks:
    default:
        name: miaoma-docs-network
        driver: bridge
